### ISSUE TITLE
Develop Treatment Logic

### ISSUE THREAD

**Issue by awasserman14** [awasserman14/OsteoApp#12]
Establish decision tree for treatments based on survey results

**Comment by austinduncan1** [comment]
Develop the 'algorithm' that makes and outputs treatments in an order based upon the users survey answers.

More discussion required with the client to understand how this order/ranking needs to be achieved.

**Comment by austinduncan1** [comment]
@awasserman14 I was thinking we may want to convert this to an Epic--we could set it up so that as we progress through the semester we are refining the algorithm to output the treatments list.  In the beginning it could just be something very basic?

This way we won't risk getting bottlenecked by this task.

**Comment by austinduncan1** [comment]
Currently only outputting "stock" results; This will be updated at a future time, once our client has met with medical professionals to determine more information.

**Comment by ghost** [comment]
Algorithm is limited due to professional constraints.
